<a href="https://colab.research.google.com/github/HimanshuGitCode/Learning-CampusX-/blob/main/NumPy_(Class_1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Creating NumPy Arrays

import numpy as np #importing NumPY

a = np.array([1,2,3]) #NumPy Array Created(1D Array)
print(a) #print function
print(type(a)) #type of data types

#1D Array is also know as Vector

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
#2D NumPy Array

b= np.array ([[1,2,3],[4,5,6]])
print(b)

#2D and 3D Array is also know as matrix.

[[1 2 3]
 [4 5 6]]


In [4]:
#3D Array

c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

#3D NumPy array is also know as Tensor.

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
#Custom Data Types NumPy Array (Float)

np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [6]:
#Custom Data Types NumPy Array (Bool)

np.array([1,2,3,0],dtype= bool)

array([ True,  True,  True, False])

In [7]:
#Custom Data Types NumPy Array (Complex)

np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [8]:
#NumPy Arange (Work Like a Python Range[Frist one Included and Last one Excluded])

#Array can be created with Array and Arange

np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
#NumPy Arange With Gap (4 Will be taken as Arange)

np.arange(1,20,4)

array([ 1,  5,  9, 13, 17])

In [10]:
#NumPy Function Reshape

np.arange(1,11).reshape(5,2) #(5 is row and 2 is column)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [11]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
#NumPy Aray Ones

np.ones((3,4))

#Use Case of Np.ones:- Use in Neural Network and Use in Deep Learning and Use in intialization

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
#NumPy Array Zero

np.zeros((4,3))



array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
#NumPy Random

np.random.random((3,4))

#Intialize With random Number

array([[0.3426045 , 0.12396662, 0.73551543, 0.40657812],
       [0.03181752, 0.72068545, 0.20894505, 0.11644991],
       [0.90185074, 0.15564291, 0.88502331, 0.54330436]])

In [15]:
#NumPy LinSpace
#in a given rage it give number with equally distance

np.linspace(-10,10,10) #(-10(lower Range) se lekar 10(Upper Range) tak 10(Number of intem that you want) number genrate kar ke do)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [16]:
#np.identity

#Indetity Matrix is that martix which diagnoal item are 1 and other diagonal item is zero

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# **Array Attributes**

In [17]:
a1 = np.arange(10) #1d array (vector)
a2 = np.arange(12,dtype=float).reshape(3,4) #Matrix
a3 = np.arange(8).reshape(2,2,2) #Tesor (3d)


In [18]:
#ndim (Number of dimension)

print(a1.ndim) #1d array
print(a2.ndim) #2d Array
print(a3.ndim) #3d Array


1
2
3


In [20]:
#Shape

print(a1.shape) #1d array
print(a2.shape) #2d Array
print(a3.shape) #3d Array

(10,)
(3, 4)
(2, 2, 2)


In [21]:
#Size
print(a1.size) #1d array
print(a2.size) #2d Array
print(a3.size) #3d Array

10
12
8


In [22]:
#Item Size
print(a1.itemsize) #1d array 32Bit integer (4Byte)
print(a2.itemsize) #2d Array
print(a3.itemsize) #3d Array


4
8
4


In [24]:
#Data Type

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


# **Changing Datatype** 

In [38]:
#astype = It is used to change the data type of the array

#it can also help to optimize the memory where we have to need small number we can take 32 bit
a3.astype(np.int64)
a3.dtype 

dtype('int32')

# **Array Operations**

In [40]:
a1= np.arange(12).reshape(3,4)
a2= np.arange(12,24).reshape(3,4)



array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [41]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [43]:
#Scalar Operation
a1 * 2 #it can multiply each element by 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [47]:
#Relational Operation

a2>12 #it will ask each number in a2 that you are grater than 5 or not and if yes it will giver answer in boolean
#it can work is greater than,less than , equal to, not equal to etc.

array([[False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [52]:
#Vector Operation
#shape should be same
a1+a2 #it will add each elment of a1 and a2 it also work with multiplication,substract,divsion , addtion etc.

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

# **Array Function**

In [55]:
a1 = np.random.random((3,4))
a1 = np.round(a1*100)
a1

array([[  5.,  93., 100.,  17.],
       [ 67.,  95.,  44.,  38.],
       [ 13.,  83.,  45.,  69.]])

In [56]:
 #Max/Min/Sum/Prod
 np.max(a1) #Maximum Numbers 

100.0

In [57]:
np.min(a1) #Minimum Numbers 

5.0

In [58]:
np.sum(a1) #Sum of all the Numbers

669.0

In [59]:
np.prod(a1) #Product of all the Numbers

2.81851015920903e+19

In [60]:
 #if you want minimum, maximum, sum and product of each row and column
 
 np.max(a1,axis=0) #Column wise

array([ 67.,  95., 100.,  69.])

In [61]:
 np.max(a1,axis=1) #Row wise

array([100.,  95.,  83.])

In [62]:
 np.prod(a1,axis=0) #Column wise Multiplication

array([  4355., 733305., 198000.,  44574.])

In [63]:
 np.prod(a1,axis=1) #Row wise Multiplication

array([  790500., 10642280.,  3350295.])

In [69]:
#Statical Function

print(np.mean(a1)) #Mean of a1 matixes
print(np.median(a1)) #Median of a1 matixes

#Row and Column Wise Mean

print(np.mean(a1,axis = 1)) #Row Wise
print(np.mean(a1, axis = 0)) #Column Wise

#Row and Column Wise Median

print(np.mean(a1, axis = 1)) #Row Wise
print(np.mean(a1, axis = 0)) #Column Wise

55.75
56.0
[53.75 61.   52.5 ]
[28.33333333 90.33333333 63.         41.33333333]
[53.75 61.   52.5 ]
[28.33333333 90.33333333 63.         41.33333333]


In [75]:
#Standard Deviation

print(np.std(a1))

#Starndard Deviaiton Row and Column Wise

print(np.std(a1,axis = 1)) #Row Wise
print(np.std(a1,axis = 0)) #Column Wise

32.151010870577615
[43.03123865 22.41651177 26.5471279 ]
[27.53583524  5.24933858 26.16613588 21.35935912]


In [77]:
#variance = Variance is a statistical measurement that shows how far each number in the array is spread out from the mean

print(np.var(a1))
print(np.var(a1,axis = 1)) #Row Wise
print(np.var(a1,axis = 0)) #Column Wise

1033.6875
[1851.6875  502.5     704.75  ]
[758.22222222  27.55555556 684.66666667 456.22222222]


In [79]:
#Trignometric Function (Sin, Cos, Tan)

print(np.sin(a1))
print(np.cos(a1))
print(np.tan(a1))



[[-0.95892427 -0.94828214 -0.50636564 -0.96139749]
 [-0.85551998  0.68326171  0.01770193  0.29636858]
 [ 0.42016704  0.96836446  0.85090352 -0.11478481]]
[[ 0.28366219  0.3174287   0.86231887 -0.27516334]
 [-0.5177698   0.73017356  0.99984331  0.95507364]
 [ 0.90744678  0.24954012  0.52532199  0.99339038]]
[[-3.38051501 -2.98738626 -0.58721392  3.49391565]
 [ 1.65231726  0.93575247  0.0177047   0.31030966]
 [ 0.46302113  3.88059631  1.61977519 -0.11554855]]


In [82]:
#Dot Product:- taking the sum of a list comprehension performing element-wise multiplication

# we have to check first martix colum and second martix row should be same
 
a2 = np.arange(12).reshape(3,4) #3 columns and 4 rows
a3= np.arange(12,24).reshape(4,3)

np.dot(a2,a3) #it will give 3,3 matrix  

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])