<a href="https://colab.research.google.com/github/HimanshuGitCode/Learning-CampusX-/blob/main/NumPy_(Class_1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Creating NumPy Arrays

import numpy as np #importing NumPY

a = np.array([1,2,3]) #NumPy Array Created(1D Array)
print(a) #print function
print(type(a)) #type of data types

#1D Array is also know as Vector

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
#2D NumPy Array

b= np.array ([[1,2,3],[4,5,6]])
print(b)

#2D and 3D Array is also know as matrix.

[[1 2 3]
 [4 5 6]]


In [4]:
#3D Array

c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

#3D NumPy array is also know as Tensor.

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
#Custom Data Types NumPy Array (Float)

np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [6]:
#Custom Data Types NumPy Array (Bool)

np.array([1,2,3,0],dtype= bool)

array([ True,  True,  True, False])

In [7]:
#Custom Data Types NumPy Array (Complex)

np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [8]:
#NumPy Arange (Work Like a Python Range[Frist one Included and Last one Excluded])

#Array can be created with Array and Arange

np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
#NumPy Arange With Gap (4 Will be taken as Arange)

np.arange(1,20,4)

array([ 1,  5,  9, 13, 17])

In [10]:
#NumPy Function Reshape

np.arange(1,11).reshape(5,2) #(5 is row and 2 is column)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [11]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
#NumPy Aray Ones

np.ones((3,4))

#Use Case of Np.ones:- Use in Neural Network and Use in Deep Learning and Use in intialization

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
#NumPy Array Zero

np.zeros((4,3))



array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
#NumPy Random

np.random.random((3,4))

#Intialize With random Number

array([[0.26171625, 0.81276343, 0.50777022, 0.63005568],
       [0.69871024, 0.17136742, 0.48546026, 0.74639706],
       [0.01124352, 0.22754215, 0.87488084, 0.94715773]])

In [26]:
#NumPy LinSpace
#in a given rage it give number with equally distance

np.linspace(-10,10,10) #(-10(lower Range) se lekar 10(Upper Range) tak 10(Number of intem that you want) number genrate kar ke do)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [27]:
#np.identity

#Indetity Matrix is that martix which diagnoal item are 1 and other diagonal item is zero

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# **Array Attributes**

In [19]:
a1 = np.arange(10) #1d array (vector)
a2 = np.arange(12,dtype=float).reshape(3,4) #Matrix
a3 = np.arange(8).reshape(2,2,2) #Tesor (3d)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [21]:
#ndim (Number of dimension)

print(a1.ndim) #1d array
print(a2.ndim) #2d Array
print(a3.ndim) #3d Array


1
2
3
