<a href="https://colab.research.google.com/github/HimanshuGitCode/Learning-CampusX-/blob/main/NumPy_(Class_1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Creating NumPy Arrays

import numpy as np #importing NumPY

a = np.array([1,2,3]) #NumPy Array Created(1D Array)
print(a) #print function
print(type(a)) #type of data types

#1D Array is also know as Vector

[1 2 3]
<class 'numpy.ndarray'>


In [2]:
#2D NumPy Array

b= np.array ([[1,2,3],[4,5,6]])
print(b)

#2D and 3D Array is also know as matrix.

[[1 2 3]
 [4 5 6]]


In [3]:
#3D Array

c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

#3D NumPy array is also know as Tensor.

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#Custom Data Types NumPy Array (Float)

np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [5]:
#Custom Data Types NumPy Array (Bool)

np.array([1,2,3,0],dtype= bool)

array([ True,  True,  True, False])

In [6]:
#Custom Data Types NumPy Array (Complex)

np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [7]:
#NumPy Arange (Work Like a Python Range[Frist one Included and Last one Excluded])

#Array can be created with Array and Arange

np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
#NumPy Arange With Gap (4 Will be taken as Arange)

np.arange(1,20,4)

array([ 1,  5,  9, 13, 17])

In [9]:
#NumPy Function Reshape

np.arange(1,11).reshape(5,2) #(5 is row and 2 is column)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [10]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
#NumPy Aray Ones

np.ones((3,4))

#Use Case of Np.ones:- Use in Neural Network and Use in Deep Learning and Use in intialization

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
#NumPy Array Zero

np.zeros((4,3))



array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
#NumPy Random

np.random.random((3,4))

#Intialize With random Number

array([[0.75176765, 0.16153435, 0.17992518, 0.75038628],
       [0.44314622, 0.85363039, 0.37481694, 0.1410487 ],
       [0.02519766, 0.16113958, 0.98547265, 0.67200113]])

In [14]:
#NumPy LinSpace
#in a given rage it give number with equally distance

np.linspace(-10,10,10) #(-10(lower Range) se lekar 10(Upper Range) tak 10(Number of intem that you want) number genrate kar ke do)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [15]:
#np.identity

#Indetity Matrix is that martix which diagnoal item are 1 and other diagonal item is zero

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# **Array Attributes**

In [16]:
a1 = np.arange(10) #1d array (vector)
a2 = np.arange(12,dtype=float).reshape(3,4) #Matrix
a3 = np.arange(8).reshape(2,2,2) #Tesor (3d)


In [17]:
#ndim (Number of dimension)

print(a1.ndim) #1d array
print(a2.ndim) #2d Array
print(a3.ndim) #3d Array


1
2
3


In [18]:
#Shape

print(a1.shape) #1d array
print(a2.shape) #2d Array
print(a3.shape) #3d Array

(10,)
(3, 4)
(2, 2, 2)


In [19]:
#Size
print(a1.size) #1d array
print(a2.size) #2d Array
print(a3.size) #3d Array

10
12
8


In [20]:
#Item Size
print(a1.itemsize) #1d array 32Bit integer (4Byte)
print(a2.itemsize) #2d Array
print(a3.itemsize) #3d Array


4
8
4


In [21]:
#Data Type

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


# **Changing Datatype** 

In [22]:
#astype = It is used to change the data type of the array

#it can also help to optimize the memory where we have to need small number we can take 32 bit
a3.astype(np.int64)
a3.dtype 

dtype('int32')

# **Array Operations**

In [23]:
a1= np.arange(12).reshape(3,4)
a2= np.arange(12,24).reshape(3,4)



In [24]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [26]:
#Scalar Operation
a1 * 2 #it can multiply each element by 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [27]:
#Relational Operation

a2>12 #it will ask each number in a2 that you are grater than 5 or not and if yes it will giver answer in boolean
#it can work is greater than,less than , equal to, not equal to etc.

array([[False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [28]:
#Vector Operation
#shape should be same
a1+a2 #it will add each elment of a1 and a2 it also work with multiplication,substract,divsion , addtion etc.

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

# **Array Function**

In [29]:
a1 = np.random.random((3,4))
a1 = np.round(a1*100)
a1

array([[15., 92., 48., 31.],
       [60., 79., 35., 87.],
       [94., 97., 76., 91.]])

In [30]:
 #Max/Min/Sum/Prod
 np.max(a1) #Maximum Numbers 

97.0

In [31]:
np.min(a1) #Minimum Numbers 

15.0

In [32]:
np.sum(a1) #Sum of all the Numbers

805.0

In [33]:
np.prod(a1) #Product of all the Numbers

1.8689695628456884e+21

In [34]:
 #if you want minimum, maximum, sum and product of each row and column
 
 np.max(a1,axis=0) #Column wise

array([94., 97., 76., 91.])

In [35]:
 np.max(a1,axis=1) #Row wise

array([92., 87., 97.])

In [36]:
 np.prod(a1,axis=0) #Column wise Multiplication

array([ 84600., 704996., 127680., 245427.])

In [37]:
 np.prod(a1,axis=1) #Row wise Multiplication

array([ 2053440., 14433300., 63060088.])

In [38]:
#Statical Function

print(np.mean(a1)) #Mean of a1 matixes
print(np.median(a1)) #Median of a1 matixes

#Row and Column Wise Mean

print(np.mean(a1,axis = 1)) #Row Wise
print(np.mean(a1, axis = 0)) #Column Wise

#Row and Column Wise Median

print(np.mean(a1, axis = 1)) #Row Wise
print(np.mean(a1, axis = 0)) #Column Wise

67.08333333333333
77.5
[46.5  65.25 89.5 ]
[56.33333333 89.33333333 53.         69.66666667]
[46.5  65.25 89.5 ]
[56.33333333 89.33333333 53.         69.66666667]


In [39]:
#Standard Deviation

print(np.std(a1))

#Starndard Deviaiton Row and Column Wise

print(np.std(a1,axis = 1)) #Row Wise
print(np.std(a1,axis = 0)) #Column Wise

27.216595223421237
[28.7445647  20.0296655   8.07774721]
[32.35566239  7.58653778 17.10750323 27.39018478]


In [40]:
#variance = Variance is a statistical measurement that shows how far each number in the array is spread out from the mean

print(np.var(a1))
print(np.var(a1,axis = 1)) #Row Wise
print(np.var(a1,axis = 0)) #Column Wise

740.7430555555557
[826.25   401.1875  65.25  ]
[1046.88888889   57.55555556  292.66666667  750.22222222]


In [41]:
#Trignometric Function (Sin, Cos, Tan)

print(np.sin(a1))
print(np.cos(a1))
print(np.tan(a1))



[[ 0.65028784 -0.77946607 -0.76825466 -0.40403765]
 [-0.30481062 -0.44411267 -0.42818267 -0.82181784]
 [-0.24525199  0.37960774  0.56610764  0.10598751]]
[[-0.75968791 -0.62644445 -0.64014434  0.91474236]
 [-0.95241298 -0.89597095 -0.90369221  0.56975033]
 [ 0.96945937 -0.92514754  0.82433133 -0.99436746]]
[[-0.8559934   1.24427006  1.20012724 -0.44169557]
 [ 0.32004039  0.49567753  0.47381472 -1.44241747]
 [-0.2529781  -0.4103213   0.68674769 -0.10658787]]


In [42]:
#Dot Product:- taking the sum of a list comprehension performing element-wise multiplication

# we have to check first martix colum and second martix row should be same
 
a2 = np.arange(12).reshape(3,4) #3 columns and 4 rows
a3= np.arange(12,24).reshape(4,3)

np.dot(a2,a3) #it will give 3,3 matrix  

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [44]:
#log and exponents

print(np.exp(a1)) #exponential
print(np.log(a1)) #log 

[[3.26901737e+06 9.01762841e+39 7.01673591e+20 2.90488497e+13]
 [1.14200739e+26 2.03828107e+34 1.58601345e+15 6.07603023e+37]
 [6.66317622e+40 1.33833472e+42 1.01480039e+33 3.31740010e+39]]
[[2.7080502  4.52178858 3.87120101 3.4339872 ]
 [4.09434456 4.36944785 3.55534806 4.46590812]
 [4.54329478 4.57471098 4.33073334 4.51085951]]


In [47]:
 #Round , Floor and Ceil
 
 np.round(np.random.random((2,3))*100) #it will make roundoff the nearest number


array([[88., 83.,  2.],
       [ 1., 72., 46.]])

In [58]:
np.floor(np.random.random((2,3))*100) #it will take the floor value of the number means it will take back lowest number

array([[60., 77., 29.],
       [46., 65., 23.]])

In [61]:
 np.ceil(np.random.random((2,3))*100) #if it 6.1 it will take to 7

array([[52.,  9., 70.],
       [25., 20., 60.]])

# *Indexing and Slicing*

In [65]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [66]:
a1 #1d array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
a2 #2d array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
a3 #3d array

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [71]:
print(a1[-1]) #it will give last element of the array

print(a1[0]) #it will give first element of the array

9
0


In [72]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [79]:
#i have to access 6 number

#to find out the item in the array we have to give the row and column number

print(a2[1,2]) #it will give 6 number 

print(a2[2,1])  #2 row [8,9,10,11] and 1 column [9]

print(a2[1,0])

6
9
4


In [81]:
#3D Array Accessing 

a3  

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [87]:
a3[0,1,1] #3d array is made up of 2 2d array and 2 1d array so we have to give 3 index number to find out the number

print(a3[0,1,0])
print(a3[1,1,0])

2
6
